### ISSUE TITLE
Where is BertTagger?

### ISSUE THREAD

**Issue by Zhangyunyan77** [TanyaZhao/MRC4ERE_plus#2]
I cannot find BertTagger. Did you forget to upload the model file?

**Comment by Amling2017** [comment]
(base) F:\project\MRC4ERE_plus-master\run>python run_tagger.py
Traceback (most recent call last):
  File "run_tagger.py", line 26, in <module>
    from models.bert_mrc import BertTagger
ModuleNotFoundError: No module named 'models'

**Comment by Amling2017** [comment]
Traceback (most recent call last):
  File "run_tagger.py", line 360, in <module>
    main()
  File "run_tagger.py", line 356, in main
    train(tokenizer, model, optimizer, train_loader, dev_loader, test_loader, config, device, n_gpu, label_list, num_train_steps)
  File "run_tagger.py", line 184, in train
    label_list, "test", tokenizer, ent_weight, rel_weight)
  File "run_tagger.py", line 241, in eval_checkpoint
    with open(entity_result_file, "w") as fw:
FileNotFoundError: [Errno 2] No such file or directory: '../log/output_results/entity_vote_best_q.output'
